-- 记账小程序数据库初始化脚本
-- MySQL 8.0+
-- Generated: 2026-07-21

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_no` VARCHAR(32) NOT NULL COMMENT '用户业务编号',
  `nick_name` VARCHAR(64) NOT NULL COMMENT '用户昵称',
  `avatar_url` VARCHAR(512) DEFAULT NULL COMMENT '头像地址',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '默认时区',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0冻结，1正常，2注销',
  `last_login_time` DATETIME(3) DEFAULT NULL COMMENT '最后登录时间',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_user_no` (`user_no`),
  KEY `idx_sys_user_status` (`status`)
) ENGINE=InnoDB COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `sys_user_auth` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `provider` VARCHAR(32) NOT NULL COMMENT '身份提供方：WECHAT、PHONE等',
  `openid` VARCHAR(128) NOT NULL COMMENT '微信openid或第三方身份标识',
  `unionid` VARCHAR(128) DEFAULT NULL COMMENT '微信unionid',
  `session_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '会话版本',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_auth_provider_openid` (`provider`, `openid`),
  KEY `idx_user_auth_user_id` (`user_id`),
  KEY `idx_user_auth_unionid` (`unionid`),
  CONSTRAINT `fk_user_auth_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='用户第三方身份表';

CREATE TABLE IF NOT EXISTS `fin_book` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `book_no` VARCHAR(32) NOT NULL COMMENT '账本业务编号',
  `owner_user_id` BIGINT UNSIGNED NOT NULL COMMENT '账本所有者用户ID',
  `name` VARCHAR(64) NOT NULL COMMENT '账本名称',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '账本说明',
  `cover_url` VARCHAR(512) DEFAULT NULL COMMENT '封面地址',
  `currency_code` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '默认币种',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '账本时区',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0关闭，1正常，2归档',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_book_book_no` (`book_no`),
  KEY `idx_fin_book_owner_status` (`owner_user_id`, `status`),
  CONSTRAINT `fk_fin_book_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='账本表';

CREATE TABLE IF NOT EXISTS `fin_book_member` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `role` VARCHAR(16) NOT NULL DEFAULT 'MEMBER' COMMENT '角色：OWNER、ADMIN、MEMBER、VIEWER',
  `permissions` JSON DEFAULT NULL COMMENT '扩展权限配置',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0退出，1正常，2邀请中',
  `invited_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '邀请人用户ID',
  `joined_time` DATETIME(3) DEFAULT NULL COMMENT '加入时间',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_member_book_user` (`book_id`, `user_id`),
  KEY `idx_book_member_user_status` (`user_id`, `status`),
  KEY `idx_book_member_invited_by` (`invited_by`),
  CONSTRAINT `fk_book_member_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_book_member_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_book_member_inviter` FOREIGN KEY (`invited_by`) REFERENCES `sys_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='账本成员表';

CREATE TABLE IF NOT EXISTS `fin_category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_no` VARCHAR(32) NOT NULL COMMENT '分类业务编号',
  `scope_type` VARCHAR(16) NOT NULL DEFAULT 'BOOK' COMMENT '范围：SYSTEM、BOOK',
  `book_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '账本ID，系统分类为空',
  `category_type` VARCHAR(16) NOT NULL COMMENT '分类类型：EXPENSE、INCOME',
  `parent_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '父分类ID',
  `name` VARCHAR(64) NOT NULL COMMENT '分类名称',
  `icon` VARCHAR(64) DEFAULT NULL COMMENT '分类图标',
  `color` VARCHAR(16) DEFAULT NULL COMMENT '分类颜色',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `system_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否系统分类',
  `hidden_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否隐藏',
  `deleted_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_category_no` (`category_no`),
  KEY `idx_category_book_type` (`book_id`, `category_type`, `hidden_flag`, `deleted_flag`),
  KEY `idx_category_parent` (`parent_id`),
  CONSTRAINT `fk_category_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_category_parent` FOREIGN KEY (`parent_id`) REFERENCES `fin_category` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `ck_category_scope_book` CHECK ((`scope_type` = 'SYSTEM' AND `book_id` IS NULL) OR (`scope_type` = 'BOOK' AND `book_id` IS NOT NULL))
) ENGINE=InnoDB COMMENT='收支分类表';

CREATE TABLE IF NOT EXISTS `fin_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `account_no` VARCHAR(32) NOT NULL COMMENT '账户业务编号',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `name` VARCHAR(64) NOT NULL COMMENT '账户名称',
  `account_type` VARCHAR(32) NOT NULL COMMENT '账户类型：CASH、BANK、WECHAT、ALIPAY、CREDIT',
  `account_nature` VARCHAR(16) NOT NULL DEFAULT 'ASSET' COMMENT '账户性质：ASSET、LIABILITY',
  `initial_balance` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '初始余额',
  `current_balance` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '当前余额快照',
  `included_in_assets` TINYINT NOT NULL DEFAULT 1 COMMENT '是否计入总资产',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常，2归档',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `deleted_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_account_no` (`account_no`),
  KEY `idx_account_book_status` (`book_id`, `status`, `deleted_flag`),
  CONSTRAINT `fk_account_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='账户表';

CREATE TABLE IF NOT EXISTS `fin_transaction` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `transaction_no` VARCHAR(40) NOT NULL COMMENT '交易业务流水号',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '客户端幂等请求号',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `created_user_id` BIGINT UNSIGNED NOT NULL COMMENT '记账用户ID',
  `transaction_type` VARCHAR(16) NOT NULL COMMENT '类型：EXPENSE、INCOME、TRANSFER、ADJUSTMENT、BORROW、LEND、REPAYMENT',
  `category_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '分类ID',
  `original_transaction_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '原交易ID，用于冲正或复制追踪',
  `amount` DECIMAL(19,2) NOT NULL COMMENT '交易金额',
  `currency_code` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `happened_at` DATETIME(3) NOT NULL COMMENT '业务发生时间',
  `title` VARCHAR(128) NOT NULL COMMENT '账单标题',
  `note` VARCHAR(1000) DEFAULT NULL COMMENT '备注',
  `status` VARCHAR(16) NOT NULL DEFAULT 'EFFECTIVE' COMMENT '状态：EFFECTIVE、VOIDED、REVERSED',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_transaction_no` (`transaction_no`),
  UNIQUE KEY `uk_transaction_user_request` (`book_id`, `created_user_id`, `request_id`),
  KEY `idx_transaction_book_time` (`book_id`, `happened_at`, `id`),
  KEY `idx_transaction_book_category_time` (`book_id`, `category_id`, `happened_at`),
  KEY `idx_transaction_user_time` (`created_user_id`, `happened_at`),
  KEY `idx_transaction_original` (`original_transaction_id`),
  CONSTRAINT `fk_transaction_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_user` FOREIGN KEY (`created_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_category` FOREIGN KEY (`category_id`) REFERENCES `fin_category` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_original` FOREIGN KEY (`original_transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_transaction_amount_positive` CHECK (`amount` > 0)
) ENGINE=InnoDB COMMENT='账单交易主表';

CREATE TABLE IF NOT EXISTS `fin_account_entry` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `transaction_id` BIGINT UNSIGNED NOT NULL COMMENT '交易ID',
  `account_id` BIGINT UNSIGNED NOT NULL COMMENT '账户ID',
  `entry_type` VARCHAR(16) NOT NULL COMMENT '分录类型：INCREASE、DECREASE、REVERSAL',
  `signed_amount` DECIMAL(19,2) NOT NULL COMMENT '带正负号的余额变动值',
  `balance_before` DECIMAL(19,2) NOT NULL COMMENT '变动前余额',
  `balance_after` DECIMAL(19,2) NOT NULL COMMENT '变动后余额',
  `happened_at` DATETIME(3) NOT NULL COMMENT '业务发生时间',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_account_entry_transaction` (`transaction_id`),
  KEY `idx_account_entry_account_time` (`account_id`, `happened_at`, `id`),
  CONSTRAINT `fk_account_entry_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_account_entry_account` FOREIGN KEY (`account_id`) REFERENCES `fin_account` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_account_entry_nonzero` CHECK (`signed_amount` <> 0),
  CONSTRAINT `ck_account_entry_balance` CHECK (`balance_after` = `balance_before` + `signed_amount`)
) ENGINE=InnoDB COMMENT='账户余额变动分录表';

CREATE TABLE IF NOT EXISTS `fin_attachment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `transaction_id` BIGINT UNSIGNED NOT NULL COMMENT '交易ID',
  `storage_provider` VARCHAR(32) NOT NULL COMMENT '存储提供方',
  `object_key` VARCHAR(512) NOT NULL COMMENT '对象存储Key',
  `file_name` VARCHAR(255) NOT NULL COMMENT '原始文件名',
  `content_type` VARCHAR(128) NOT NULL COMMENT 'MIME类型',
  `file_size` BIGINT UNSIGNED NOT NULL COMMENT '文件大小，字节',
  `file_hash` VARCHAR(128) DEFAULT NULL COMMENT '文件哈希',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0失效，1有效',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_attachment_object_key` (`object_key`),
  KEY `idx_attachment_transaction` (`transaction_id`, `status`),
  CONSTRAINT `fk_attachment_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_attachment_file_size` CHECK (`file_size` > 0)
) ENGINE=InnoDB COMMENT='账单附件表';

CREATE TABLE IF NOT EXISTS `fin_budget` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `budget_no` VARCHAR(32) NOT NULL COMMENT '预算业务编号',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `budget_month` CHAR(7) NOT NULL COMMENT '预算月份，格式YYYY-MM',
  `total_limit` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '总预算额度',
  `warning_rate` DECIMAL(5,4) NOT NULL DEFAULT 0.8000 COMMENT '预警比例',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1有效',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_budget_no` (`budget_no`),
  UNIQUE KEY `uk_budget_book_month` (`book_id`, `budget_month`),
  CONSTRAINT `fk_budget_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_budget_month` CHECK (`budget_month` REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT `ck_budget_total_limit` CHECK (`total_limit` >= 0),
  CONSTRAINT `ck_budget_warning_rate` CHECK (`warning_rate` > 0 AND `warning_rate` <= 1)
) ENGINE=InnoDB COMMENT='月度预算表';

CREATE TABLE IF NOT EXISTS `fin_budget_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `budget_id` BIGINT UNSIGNED NOT NULL COMMENT '预算ID',
  `category_id` BIGINT UNSIGNED NOT NULL COMMENT '分类ID',
  `limit_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '分类预算额度',
  `warning_rate` DECIMAL(5,4) NOT NULL DEFAULT 0.8000 COMMENT '预警比例',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_budget_item_category` (`budget_id`, `category_id`),
  KEY `idx_budget_item_category` (`category_id`),
  CONSTRAINT `fk_budget_item_budget` FOREIGN KEY (`budget_id`) REFERENCES `fin_budget` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_budget_item_category` FOREIGN KEY (`category_id`) REFERENCES `fin_category` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_budget_item_limit` CHECK (`limit_amount` >= 0),
  CONSTRAINT `ck_budget_item_warning_rate` CHECK (`warning_rate` > 0 AND `warning_rate` <= 1)
) ENGINE=InnoDB COMMENT='分类预算表';

CREATE TABLE IF NOT EXISTS `fin_loan_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `loan_no` VARCHAR(32) NOT NULL COMMENT '借还业务编号',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `created_user_id` BIGINT UNSIGNED NOT NULL COMMENT '创建用户ID',
  `loan_type` VARCHAR(16) NOT NULL COMMENT '类型：BORROW、LEND',
  `counterparty_name` VARCHAR(128) NOT NULL COMMENT '往来人名称',
  `total_amount` DECIMAL(19,2) NOT NULL COMMENT '总金额',
  `repaid_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '已还金额',
  `due_date` DATE DEFAULT NULL COMMENT '到期日',
  `status` VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '状态：OPEN、PARTIAL、CLOSED、OVERDUE',
  `related_transaction_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联交易ID',
  `note` VARCHAR(1000) DEFAULT NULL COMMENT '备注',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fin_loan_no` (`loan_no`),
  KEY `idx_loan_book_status_due` (`book_id`, `status`, `due_date`),
  KEY `idx_loan_user` (`created_user_id`),
  KEY `idx_loan_transaction` (`related_transaction_id`),
  CONSTRAINT `fk_loan_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_loan_user` FOREIGN KEY (`created_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_loan_transaction` FOREIGN KEY (`related_transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_loan_amount` CHECK (`total_amount` > 0),
  CONSTRAINT `ck_loan_repaid_amount` CHECK (`repaid_amount` >= 0 AND `repaid_amount` <= `total_amount`)
) ENGINE=InnoDB COMMENT='借还记录表';

CREATE TABLE IF NOT EXISTS `fin_daily_summary` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `summary_date` DATE NOT NULL COMMENT '汇总日期',
  `dimension_type` VARCHAR(16) NOT NULL DEFAULT 'BOOK' COMMENT '维度：BOOK、CATEGORY、ACCOUNT',
  `dimension_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '维度ID，账本汇总为0',
  `income_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '收入金额',
  `expense_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '支出金额',
  `transaction_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易数量',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_daily_summary_dimension` (`book_id`, `summary_date`, `dimension_type`, `dimension_id`),
  KEY `idx_daily_summary_date` (`summary_date`),
  CONSTRAINT `fk_daily_summary_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `ck_daily_summary_amount` CHECK (`income_amount` >= 0 AND `expense_amount` >= 0)
) ENGINE=InnoDB COMMENT='日统计汇总表';

CREATE TABLE IF NOT EXISTS `fin_monthly_summary` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `summary_month` CHAR(7) NOT NULL COMMENT '汇总月份，格式YYYY-MM',
  `dimension_type` VARCHAR(16) NOT NULL DEFAULT 'BOOK' COMMENT '维度：BOOK、CATEGORY、ACCOUNT',
  `dimension_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '维度ID，账本汇总为0',
  `income_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '收入金额',
  `expense_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '支出金额',
  `balance_amount` DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT '结余金额',
  `transaction_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易数量',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_monthly_summary_dimension` (`book_id`, `summary_month`, `dimension_type`, `dimension_id`),
  KEY `idx_monthly_summary_month` (`summary_month`),
  CONSTRAINT `fk_monthly_summary_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `ck_monthly_summary_month` CHECK (`summary_month` REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT `ck_monthly_summary_amount` CHECK (`income_amount` >= 0 AND `expense_amount` >= 0),
  CONSTRAINT `ck_monthly_summary_balance` CHECK (`balance_amount` = `income_amount` - `expense_amount`)
) ENGINE=InnoDB COMMENT='月统计汇总表';

CREATE TABLE IF NOT EXISTS `sys_export_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_no` VARCHAR(40) NOT NULL COMMENT '导出任务编号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '账本ID',
  `export_type` VARCHAR(16) NOT NULL COMMENT '导出类型：EXCEL、CSV',
  `query_json` JSON DEFAULT NULL COMMENT '导出查询条件',
  `task_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、PROCESSING、SUCCESS、FAILED',
  `file_object_key` VARCHAR(512) DEFAULT NULL COMMENT '导出文件对象Key',
  `failure_reason` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `started_time` DATETIME(3) DEFAULT NULL COMMENT '开始时间',
  `finished_time` DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  `expired_time` DATETIME(3) DEFAULT NULL COMMENT '文件过期时间',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_export_task_no` (`task_no`),
  KEY `idx_export_task_user_status` (`user_id`, `task_status`, `created_time`),
  KEY `idx_export_task_expired` (`expired_time`),
  CONSTRAINT `fk_export_task_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_export_task_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='异步导出任务表';

CREATE TABLE IF NOT EXISTS `sys_operation_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '链路追踪ID',
  `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作用户ID',
  `book_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '账本ID',
  `operation_type` VARCHAR(32) NOT NULL COMMENT '操作类型',
  `business_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `business_id` VARCHAR(64) DEFAULT NULL COMMENT '业务对象ID',
  `change_summary` JSON DEFAULT NULL COMMENT '变更摘要',
  `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT '客户端标识',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_operation_log_user_time` (`user_id`, `created_time`),
  KEY `idx_operation_log_book_time` (`book_id`, `created_time`),
  KEY `idx_operation_log_business` (`business_type`, `business_id`),
  KEY `idx_operation_log_trace` (`trace_id`)
) ENGINE=InnoDB COMMENT='操作审计日志表';

CREATE TABLE IF NOT EXISTS `sys_outbox_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `event_no` VARCHAR(40) NOT NULL COMMENT '事件编号',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型',
  `aggregate_type` VARCHAR(32) NOT NULL COMMENT '聚合类型',
  `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合ID',
  `payload_json` JSON NOT NULL COMMENT '事件载荷',
  `event_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、PROCESSING、SUCCESS、FAILED',
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_time` DATETIME(3) DEFAULT NULL COMMENT '下次重试时间',
  `last_error` VARCHAR(1000) DEFAULT NULL COMMENT '最后失败原因',
  `published_time` DATETIME(3) DEFAULT NULL COMMENT '发布时间',
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbox_event_no` (`event_no`),
  KEY `idx_outbox_status_retry` (`event_status`, `next_retry_time`, `id`),
  KEY `idx_outbox_aggregate` (`aggregate_type`, `aggregate_id`)
) ENGINE=InnoDB COMMENT='事务Outbox事件表';

CREATE TABLE IF NOT EXISTS `sys_idempotency_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `request_id` VARCHAR(64) NOT NULL COMMENT '客户端请求ID',
  `request_hash` VARCHAR(128) DEFAULT NULL COMMENT '请求内容哈希',
  `business_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `business_id` VARCHAR(64) DEFAULT NULL COMMENT '生成的业务ID',
  `response_code` VARCHAR(32) DEFAULT NULL COMMENT '响应码',
  `response_body` JSON DEFAULT NULL COMMENT '幂等响应摘要',
  `process_status` VARCHAR(16) NOT NULL DEFAULT 'PROCESSING' COMMENT '状态：PROCESSING、SUCCESS、FAILED',
  `expired_time` DATETIME(3) NOT NULL COMMENT '过期时间',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_idempotency_user_request` (`user_id`, `request_id`),
  KEY `idx_idempotency_expired` (`expired_time`),
  CONSTRAINT `fk_idempotency_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='接口幂等记录表';
