-- Free follow-up features: reimbursement, savings, reports, backup, family sharing and subscriptions.

CREATE TABLE `fin_reimbursement` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reimbursement_no` VARCHAR(40) NOT NULL,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `expense_transaction_id` BIGINT UNSIGNED NOT NULL,
  `reimbursement_transaction_id` BIGINT UNSIGNED DEFAULT NULL,
  `expected_amount` DECIMAL(19,2) NOT NULL,
  `reimburser_name` VARCHAR(128) DEFAULT NULL,
  `submitted_date` DATE DEFAULT NULL,
  `expected_date` DATE DEFAULT NULL,
  `reimbursed_time` DATETIME(3) DEFAULT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `note` VARCHAR(1000) DEFAULT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reimbursement_no` (`reimbursement_no`),
  UNIQUE KEY `uk_reimbursement_expense` (`expense_transaction_id`),
  UNIQUE KEY `uk_reimbursement_income` (`reimbursement_transaction_id`),
  KEY `idx_reimbursement_book_status` (`book_id`, `status`, `submitted_date`),
  CONSTRAINT `fk_reimbursement_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_reimbursement_expense` FOREIGN KEY (`expense_transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_reimbursement_income` FOREIGN KEY (`reimbursement_transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_reimbursement_amount` CHECK (`expected_amount` > 0)
) ENGINE=InnoDB COMMENT='报销项目';

CREATE TABLE `fin_savings_goal` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `goal_no` VARCHAR(40) NOT NULL,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1000) DEFAULT NULL,
  `target_amount` DECIMAL(19,2) NOT NULL,
  `initial_amount` DECIMAL(19,2) NOT NULL DEFAULT 0,
  `target_account_id` BIGINT UNSIGNED DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `target_date` DATE DEFAULT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `deleted_flag` TINYINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_savings_goal_no` (`goal_no`),
  KEY `idx_savings_goal_book_status` (`book_id`, `status`, `deleted_flag`),
  CONSTRAINT `fk_savings_goal_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_savings_goal_account` FOREIGN KEY (`target_account_id`) REFERENCES `fin_account` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_savings_goal_amount` CHECK (`target_amount` > 0 AND `initial_amount` >= 0)
) ENGINE=InnoDB COMMENT='储蓄目标';

CREATE TABLE `fin_savings_contribution` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contribution_no` VARCHAR(40) NOT NULL,
  `goal_id` BIGINT UNSIGNED NOT NULL,
  `transaction_id` BIGINT UNSIGNED DEFAULT NULL,
  `contribution_type` VARCHAR(16) NOT NULL,
  `amount` DECIMAL(19,2) NOT NULL,
  `contribution_date` DATE NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'EFFECTIVE',
  `note` VARCHAR(1000) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_savings_contribution_no` (`contribution_no`),
  UNIQUE KEY `uk_savings_contribution_transaction` (`transaction_id`),
  KEY `idx_savings_contribution_goal` (`goal_id`, `status`, `contribution_date`),
  CONSTRAINT `fk_savings_contribution_goal` FOREIGN KEY (`goal_id`) REFERENCES `fin_savings_goal` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_savings_contribution_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_savings_contribution_amount` CHECK (`amount` > 0)
) ENGINE=InnoDB COMMENT='储蓄目标贡献';

CREATE TABLE `fin_backup_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(40) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `file_path` VARCHAR(500) DEFAULT NULL,
  `checksum` VARCHAR(64) DEFAULT NULL,
  `format_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `task_status` VARCHAR(16) NOT NULL,
  `failure_code` VARCHAR(64) DEFAULT NULL,
  `expired_time` DATETIME(3) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_backup_task_no` (`task_no`),
  KEY `idx_backup_user_created` (`user_id`, `created_time`),
  CONSTRAINT `fk_backup_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_backup_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='加密备份任务';

CREATE TABLE `fin_restore_check` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `backup_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `added_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `skipped_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `conflict_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `report_json` JSON DEFAULT NULL,
  `status` VARCHAR(16) NOT NULL,
  `expired_time` DATETIME(3) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_restore_backup` (`backup_id`, `created_time`),
  CONSTRAINT `fk_restore_backup` FOREIGN KEY (`backup_id`) REFERENCES `fin_backup_task` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_restore_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='备份恢复检查';

CREATE TABLE `fin_duplicate_finding` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `transaction_id` BIGINT UNSIGNED NOT NULL,
  `candidate_transaction_id` BIGINT UNSIGNED NOT NULL,
  `similarity` DECIMAL(5,4) NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `handled_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_duplicate_pair` (`book_id`, `transaction_id`, `candidate_transaction_id`),
  KEY `idx_duplicate_book_status` (`book_id`, `status`, `created_time`),
  CONSTRAINT `fk_duplicate_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_duplicate_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_duplicate_candidate` FOREIGN KEY (`candidate_transaction_id`) REFERENCES `fin_transaction` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_duplicate_handler` FOREIGN KEY (`handled_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='疑似重复账单';

CREATE TABLE `fin_book_invitation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invitation_no` VARCHAR(40) NOT NULL,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `inviter_user_id` BIGINT UNSIGNED NOT NULL,
  `default_role` VARCHAR(16) NOT NULL,
  `token_hash` VARCHAR(64) NOT NULL,
  `expired_time` DATETIME(3) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  `accepted_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `accepted_time` DATETIME(3) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_invitation_no` (`invitation_no`),
  UNIQUE KEY `uk_book_invitation_token` (`token_hash`),
  KEY `idx_book_invitation_book_status` (`book_id`, `status`, `expired_time`),
  CONSTRAINT `fk_book_invitation_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_book_invitation_inviter` FOREIGN KEY (`inviter_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_book_invitation_acceptor` FOREIGN KEY (`accepted_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='账本一次性邀请';

CREATE TABLE `fin_book_audit_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `operator_user_id` BIGINT UNSIGNED NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `object_type` VARCHAR(32) NOT NULL,
  `object_id` BIGINT UNSIGNED DEFAULT NULL,
  `summary` VARCHAR(500) DEFAULT NULL,
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_book_audit_book_time` (`book_id`, `created_time`),
  CONSTRAINT `fk_book_audit_book` FOREIGN KEY (`book_id`) REFERENCES `fin_book` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_book_audit_user` FOREIGN KEY (`operator_user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='账本操作审计';

CREATE TABLE `sys_wechat_subscription` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `scene` VARCHAR(32) NOT NULL,
  `enabled_flag` TINYINT NOT NULL DEFAULT 0,
  `authorized_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_authorized_time` DATETIME(3) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modifier` VARCHAR(64) NOT NULL DEFAULT 'system',
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wechat_subscription_user_scene` (`user_id`, `scene`),
  CONSTRAINT `fk_wechat_subscription_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='微信订阅消息设置';

CREATE TABLE `sys_notification_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_key` VARCHAR(128) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `scene` VARCHAR(32) NOT NULL,
  `template_id` VARCHAR(128) DEFAULT NULL,
  `page_path` VARCHAR(255) DEFAULT NULL,
  `parameters_json` JSON DEFAULT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_retry_time` DATETIME(3) DEFAULT NULL,
  `expired_time` DATETIME(3) DEFAULT NULL,
  `failure_code` VARCHAR(64) DEFAULT NULL,
  `created_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notification_event` (`event_key`),
  KEY `idx_notification_due` (`status`, `next_retry_time`),
  CONSTRAINT `fk_notification_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='通知发送箱';
